create database AKADEMIK;

use akademik;

CREATE TABLE STRATA (
  ID_STRATA SMALLINT UNSIGNED NOT NULL,
  SINGKAT VARCHAR(10) NULL,
  STRATA VARCHAR(45) NULL,
  PRIMARY KEY(ID_STRATA)
);

CREATE TABLE SELEKSI_MASUK (
  ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL,
  SINGKAT VARCHAR(12) NULL,
  SELEKSI_MASUK VARCHAR(100) NULL,
  PRIMARY KEY(ID_SELEKSI_MASUK)
);

CREATE TABLE FAKULTAS (
  ID_FAKULTAS SMALLINT UNSIGNED NOT NULL,
  FAKULTAS VARCHAR(45) NULL,
  PRIMARY KEY(ID_FAKULTAS)
);

CREATE TABLE JURUSAN (
  ID_JURUSAN SMALLINT UNSIGNED NOT NULL,
  ID_FAKULTAS SMALLINT UNSIGNED NOT NULL,
  JURUSAN VARCHAR(45) NULL,
  PRIMARY KEY(ID_JURUSAN),
  INDEX JURUSAN_FKIndex1(ID_FAKULTAS),
  FOREIGN KEY(ID_FAKULTAS)
    REFERENCES FAKULTAS(ID_FAKULTAS)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PROGRAM_STUDI (
  ID_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL,
  ID_STRATA SMALLINT UNSIGNED NOT NULL,
  ID_JURUSAN SMALLINT UNSIGNED NOT NULL,
  PROGRAM_STUDI VARCHAR(60) NULL,
  PRIMARY KEY(ID_PROGRAM_STUDI),
  INDEX PROGRAM_STUDI_FKIndex1(ID_JURUSAN),
  INDEX PROGRAM_STUDI_FKIndex2(ID_STRATA),
  FOREIGN KEY(ID_JURUSAN)
    REFERENCES JURUSAN(ID_JURUSAN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_STRATA)
    REFERENCES STRATA(ID_STRATA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MAHASISWA (
  NIM VARCHAR(15) NOT NULL,
  ID_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL,
  ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL,
  NAMA VARCHAR(100) NULL,
  ANGKATAN SMALLINT UNSIGNED NULL,
  TGL_LAHIR DATE NULL,
  KOTA_LAHIR VARCHAR(60) NULL,
  JENIS_KELAMIN CHAR(1) NULL,
  PRIMARY KEY(NIM),
  INDEX MAHASISWA_FKIndex1(ID_SELEKSI_MASUK),
  INDEX MAHASISWA_FKIndex2(ID_PROGRAM_STUDI),
  FOREIGN KEY(ID_SELEKSI_MASUK)
    REFERENCES SELEKSI_MASUK(ID_SELEKSI_MASUK)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_PROGRAM_STUDI)
    REFERENCES PROGRAM_STUDI(ID_PROGRAM_STUDI)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

insert into fakultas (ID_FAKULTAS, FAKULTAS)
values ('1', 'Ekonomi & Bisnis'),
('2', 'Ilmu Komputer')

insert into strata (ID_STRATA, SINGKAT , STRATA)
values ('1', 'D1', 'Diploma'),
('2', 'S1', 'Sarjana'),
('3', 'S2', 'Magister')

insert into jurusan (ID_JURUSAN, ID_FAKULTAS , JURUSAN)
values ('21', '2', 'Informatika'),
('22', '2', 'Sistem Informasi'),
('23', '2', 'Teknik Komputer')

insert into seleksi_masuk (ID_SELEKSI_MASUK, SINGKAT , SELEKSI_MASUK)
values ('1', 'SNMPTN', 'SELEKSI NASIONAL MAHASISWA PERGURUAN TINGGI NEGERI'),
('2', 'SBMPTN', 'SELEKSI BERSAMA MAHASISWA PERGURUAN TINGGI NEGERI')

insert into program_studi (ID_PROGRAM_STUDI, ID_STRATA, ID_JURUSAN, PROGRAM_STUDI)
values ('211', '2', '21', 'Teknik Informatika'), 
('212', '2', '21', 'Teknik Komputer'),
('219', '3', '21', 'Magister Ilmu Komputer')

insert into mahasiswa (NIM, ID_SELEKSI_MASUK, ID_PROGRAM_STUDI, NAMA, ANGKATAN, TGL_LAHIR, KOTA_LAHIR, JENIS_KELAMIN)
values ('155150400', '1', '211', 'JONI', '2015', '1997-1-1', 'Malang', 'W'),
('155150401', '2', '212', 'JONO', '2015', '1997-10-2', 'Situbondo', 'P')

select * from mahasiswa ;

select * from fakultas ;

select * from jurusan ;

select * from program_studi ;

select * from strata ;