create schema PENJUALANDVD;

use penjualandvd;

CREATE TABLE KECAMATAN (
  ID_KECAMATAN SMALLINT UNSIGNED NOT NULL,
  KECAMATAN VARCHAR(45) NULL,
  PRIMARY KEY(ID_KECAMATAN)
);

CREATE TABLE MOVIE (
  KODE_DVD VARCHAR(10) NOT NULL,
  JUDUL VARCHAR(60) NULL,
  HARGA_SEWA DOUBLE NULL,
  DENDA DOUBLE NULL,
  TAHUN_RILIS SMALLINT UNSIGNED NULL,
  PRIMARY KEY(KODE_DVD)
);

CREATE TABLE GENRE (
  ID_GENRE SMALLINT UNSIGNED NOT NULL,
  GENRE VARCHAR(45) NULL,
  PRIMARY KEY(ID_GENRE)
);

CREATE TABLE KELURAHAN (
  ID_KELURAHAN SMALLINT UNSIGNED NOT NULL,
  ID_KECAMATAN SMALLINT UNSIGNED NOT NULL,
  KELURAHAN VARCHAR(45) NULL,
  PRIMARY KEY(ID_KELURAHAN),
  INDEX KELURAHAN_FKIndex1(ID_KECAMATAN),
  FOREIGN KEY(ID_KECAMATAN)
    REFERENCES KECAMATAN(ID_KECAMATAN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE GENRE_MOVIE (
  KODE_DVD VARCHAR(10) NOT NULL,
  ID_GENRE SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY(KODE_DVD, ID_GENRE),
  INDEX GENRE_MOVIE_FKIndex1(KODE_DVD),
  INDEX GENRE_MOVIE_FKIndex2(ID_GENRE),
  FOREIGN KEY(KODE_DVD)
    REFERENCES MOVIE(KODE_DVD)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ID_GENRE)
    REFERENCES GENRE(ID_GENRE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE PELANGGAN (
  KODE_PELANGGAN VARCHAR(10) NOT NULL,
  ID_KELURAHAN SMALLINT UNSIGNED NOT NULL,
  NAMA VARCHAR(45) NULL,
  ALAMAT VARCHAR(60) NULL,
  JENIS_KELAMIN CHAR(1) NULL,
  PRIMARY KEY(KODE_PELANGGAN),
  INDEX PELANGGAN_FKIndex1(ID_KELURAHAN),
  FOREIGN KEY(ID_KELURAHAN)
    REFERENCES KELURAHAN(ID_KELURAHAN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE KONTAK_PELANGGAN (
  NO_HP VARCHAR(25) NOT NULL,
  NO_HP_2 VARCHAR(25) NULL,
  KODE_PELANGGAN VARCHAR(10) NOT NULL,
  PRIMARY KEY(NO_HP),
  INDEX KONTAK_PELANGGAN_FKIndex1(KODE_PELANGGAN),
  FOREIGN KEY(KODE_PELANGGAN)
    REFERENCES PELANGGAN(KODE_PELANGGAN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TRANSAKSI (
  TANGGAL_SEWA DATE NOT NULL,
  KODE_DVD VARCHAR(10) NOT NULL,
  KODE_PELANGGAN VARCHAR(10) NOT NULL,
  TANGGAL_WAJIB_KEMBALI DATE NULL,
  TANGGAL_REALISASI_KEMBALI DATE NULL,
  PRIMARY KEY(TANGGAL_SEWA, KODE_DVD, KODE_PELANGGAN),
  INDEX TRANSAKSI_FKIndex1(KODE_PELANGGAN),
  INDEX TRANSAKSI_FKIndex2(KODE_DVD),
  FOREIGN KEY(KODE_PELANGGAN)
    REFERENCES PELANGGAN(KODE_PELANGGAN)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(KODE_DVD)
    REFERENCES MOVIE(KODE_DVD)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


--  UPDATE TIPE DATA

 ALTER TABLE movie 
 MODIFY COLUMN tahun_rilis year;

-- MODIFY PELANGGAN

 ALTER TABLE pelanggan
 ADD CONSTRAINT jenis_kelamin_check CHECK (JENIS_KELAMIN IN ('P', 'L'));
